# Generated by Django 5.1.2 on 2025-07-03 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_systemconfig_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('object_count', models.IntegerField(default=0)),
                ('object_classes', models.JSONField(blank=True, default=list)),
                ('confidence_scores', models.JSONField(blank=True, default=list)),
                ('camera_name', models.CharField(blank=True, max_length=100)),
                ('camera_location', models.CharField(blank=True, max_length=255)),
                ('message_body', models.TextField(blank=True)),
                ('roi_triggered', models.BooleanField(default=False)),
                ('tracking_id', models.IntegerField(blank=True, null=True)),
                ('detection_time', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_detections', to='core.camera')),
                ('detection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.detection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectDetectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.1)),
                ('detection_classes', models.JSONField(default=list)),
                ('use_camera_roi', models.BooleanField(default=True)),
                ('use_ai_assignment_roi', models.BooleanField(default=True)),
                ('alert_cooldown_seconds', models.IntegerField(default=60)),
                ('max_detections_per_minute', models.IntegerField(default=10)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('enable_telegram_notifications', models.BooleanField(default=True)),
                ('enable_snapshot_saving', models.BooleanField(default=True)),
                ('enable_video_recording', models.BooleanField(default=False)),
                ('video_duration_seconds', models.IntegerField(default=5)),
                ('video_fps', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obj_detection_config', to='core.camera')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIntrusionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('event_type', models.CharField(default='object_detection', max_length=100)),
                ('description', models.TextField()),
                ('person_count', models.IntegerField(default=0)),
                ('total_objects', models.IntegerField(default=0)),
                ('roi_coordinates', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('snapshot_saved', models.BooleanField(default=False)),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrusion_logs', to='core.camera')),
                ('obj_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.objdetection')),
            ],
            options={
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='objdetection',
            index=models.Index(fields=['camera', '-created_at'], name='detection_o_camera__8393ce_idx'),
        ),
        migrations.AddIndex(
            model_name='objdetection',
            index=models.Index(fields=['unique_id'], name='detection_o_unique__a23e80_idx'),
        ),
        migrations.AddIndex(
            model_name='objdetection',
            index=models.Index(fields=['roi_triggered', '-created_at'], name='detection_o_roi_tri_cea993_idx'),
        ),
        migrations.AddIndex(
            model_name='objdetection',
            index=models.Index(fields=['tracking_id'], name='detection_o_trackin_11b711_idx'),
        ),
        migrations.AddIndex(
            model_name='securityintrusionlog',
            index=models.Index(fields=['camera', '-event_timestamp'], name='detection_s_camera__c03e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityintrusionlog',
            index=models.Index(fields=['severity', '-event_timestamp'], name='detection_s_severit_247861_idx'),
        ),
        migrations.AddIndex(
            model_name='securityintrusionlog',
            index=models.Index(fields=['event_type', '-event_timestamp'], name='detection_s_event_t_615152_idx'),
        ),
    ]
