# Generated by Django 5.1.2 on 2025-07-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityintrusionlog',
            name='obj_detection',
        ),
        migrations.RemoveField(
            model_name='objectdetectionconfig',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='securityintrusionlog',
            name='camera',
        ),
        migrations.DeleteModel(
            name='ObjDetection',
        ),
        migrations.DeleteModel(
            name='ObjectDetectionConfig',
        ),
        migrations.DeleteModel(
            name='SecurityIntrusionLog',
        ),
    ]
