# Generated by Django 5.1.2 on 2025-06-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camera_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aimodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='is_aimodule_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='aimodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodule'),
        ),
    ]
