# Generated by Django 5.1.2 on 2025-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aimodule_camera_is_aimodule_active_camera_aimodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='description',
            field=models.TextField(default='not define'),
            preserve_default=False,
        ),
    ]
