# Generated by Django 5.1.2 on 2025-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemconfig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='roi_coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
