# Generated by Django 5.1.2 on 2025-09-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_camera_roi_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('rtsp', 'RTSP'), ('http', 'HTTP'), ('video_file', 'Video File')], default='rtsp', max_length=20),
        ),
    ]
