# Generated by Django 5.1.2 on 2025-09-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_camera_camera_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='source',
        ),
    ]
