# Generated by Django 5.1.2 on 2025-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_camera_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='detection_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='object_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
