# Generated by Django 5.1.2 on 2025-09-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_detection_detection_type_detection_object_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='frameid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PPEChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(blank=True, max_length=100, null=True)),
                ('has_helmet', models.BooleanField(default=False)),
                ('has_vest', models.BooleanField(default=False)),
                ('has_goggles', models.BooleanField(default=False)),
                ('has_gloves', models.BooleanField(default=False)),
                ('has_shoes', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, null=True)),
                ('Detectionid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.detection')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camera')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', '-Detectionid', 'trackid'], name='core_ppeche_camera__ca5aec_idx')],
            },
        ),
    ]
