# Generated by Django 5.1.2 on 2025-09-18 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_detection_frameid_ppechecks'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='intrusionChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(blank=True, max_length=100, null=True)),
                ('intrusion', models.BooleanField(default=False)),
                ('intrusion_type', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Detectionid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.detection')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camera')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', '-Detectionid', 'trackid'], name='core_intrus_camera__760676_idx')],
            },
        ),
    ]
