# Generated by Django 5.1.2 on 2025-09-19 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_camera_floor_camera_location_camera_site_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCountingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameid', models.CharField(blank=True, max_length=100, null=True)),
                ('person_id', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=50)),
                ('cumulative_in', models.IntegerField(default=0)),
                ('cumulative_out', models.IntegerField(default=0)),
                ('occupancy', models.IntegerField(default=0)),
                ('snapshot_path', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camera')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', '-timestamp'], name='core_people_camera__510a11_idx'), models.Index(fields=['direction'], name='core_people_directi_7d5eb4_idx')],
            },
        ),
    ]
