# Generated by Django 5.1.2 on 2025-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_peoplecountingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='roi_coordinates',
            field=models.TextField(blank=True, choices=[('rectangle', 'Rectangle'), ('polygon', 'Polygon'), ('line', 'Line'), ('circle', 'Circle')], help_text='Region of Interest coordinates in JSON format', null=True),
        ),
    ]
