# Generated by Django 5.1.2 on 2025-10-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_camera_roi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='roi_coordinates',
            field=models.TextField(blank=True, help_text='Region of Interest coordinates in JSON format', null=True),
        ),
    ]
